use crate::cpuregisters::{CPURegisters};
use crate::ram_controller::RamController;
use crate::{opcodes, stack};

const NMI_VECTOR: u16 = 0xFFFA;
const RESET_VECTOR: u16 = 0xFFFC;

pub struct CPU<'a> {
    pub registers: CPURegisters,
    memory: &'a mut RamController<'a>,
}

impl<'a> CPU<'_> {
    pub(crate) fn new(mem: &'a mut RamController<'a>) -> CPU<'a> {
        CPU {
            memory: mem,
            registers: CPURegisters::new()
        }
    }
    pub(crate) fn reset(&mut self) {
        self.registers = CPURegisters::new();

        let address = self.memory.read16(RESET_VECTOR);
        self.registers.set_pc(address);

        // Only used with nestest
        // self.registers.set_pc(0xC000);
    }

    pub(crate) fn trigger_nmi(&mut self) {
        let pc = self.registers.pc();
        stack::push(&mut self.registers, &mut self.memory, (pc & 0xFF) as u8);
        stack::push(&mut self.registers, &mut self.memory, ((pc >> 8) & 0xFF) as u8);

        let address = self.memory.read16(NMI_VECTOR);
        self.registers.set_pc(address);
    }

    pub(crate) fn print_foo(&self) {
        println!("ppuaddr start");
        for x in &self.memory.foobar {
            println!("{:04X}", x);
        }
        println!("ppuaddr end");
    }

    pub(crate) fn process_instruction(&mut self) -> i32 {
        if self.registers.pc() == 0xF0E9 {
            let foo = 2;
        }
        let opcode = self.memory.read8(self.registers.increment_pc());
        print!("{:02X} ", opcode);
        
        match opcode {
            0x00 => opcodes::brk_implied(&mut self.registers, &mut self.memory),
            0x01 => opcodes::ora_indirect_x(&mut self.registers, &self.memory),
            0x03 => opcodes::slo_indirect_x(&mut self.registers, &mut self.memory),
            0x04 => opcodes::nop_zero_page(&mut self.registers, &self.memory),
            0x05 => opcodes::ora_zero_page(&mut self.registers, &self.memory),
            0x06 => opcodes::asl_zero_page(&mut self.registers, &mut self.memory),
            0x07 => opcodes::slo_zero_page(&mut self.registers, &mut self.memory),
            0x08 => opcodes::php_implied(&mut self.registers, &mut self.memory),
            0x09 => opcodes::ora_immediate(&mut self.registers, &self.memory),
            0x0A => opcodes::asl_accumulator(&mut self.registers),
            0x0C => opcodes::nop_absolute(&mut self.registers, &self.memory),
            0x0D => opcodes::ora_absolute(&mut self.registers, &self.memory),
            0x0E => opcodes::asl_absolute(&mut self.registers, &mut self.memory),
            0x0F => opcodes::slo_absolute(&mut self.registers, &mut self.memory),
            0x10 => opcodes::bpl_relative(&mut self.registers, &self.memory),
            0x11 => opcodes::ora_indirect_y(&mut self.registers, &self.memory),
            0x13 => opcodes::slo_indirect_y(&mut self.registers, &mut self.memory),
            0x14 => opcodes::nop_zero_page_x(&mut self.registers, &self.memory),
            0x15 => opcodes::ora_zero_page_x(&mut self.registers, &self.memory),
            0x16 => opcodes::asl_zero_page_x(&mut self.registers, &mut self.memory),
            0x17 => opcodes::slo_zero_page_x(&mut self.registers, &mut self.memory),
            0x18 => opcodes::clc_implied(&mut self.registers),
            0x19 => opcodes::ora_absolute_y(&mut self.registers, &self.memory),
            0x1A => opcodes::nop_implied(),
            0x1B => opcodes::slo_absolute_y(&mut self.registers, &mut self.memory),
            0x1C => opcodes::nop_absolute_x(&mut self.registers, &self.memory),
            0x1D => opcodes::ora_absolute_x(&mut self.registers, &self.memory),
            0x1E => opcodes::asl_absolute_x(&mut self.registers, &mut self.memory),
            0x1F => opcodes::slo_absolute_x(&mut self.registers, &mut self.memory),
            0x20 => opcodes::jsr_absolute(&mut self.registers, &mut self.memory),
            0x21 => opcodes::and_indirect_x(&mut self.registers, &self.memory),
            0x23 => opcodes::rla_indirect_x(&mut self.registers, &mut self.memory),
            0x24 => opcodes::bit_zero_page(&mut self.registers, &self.memory),
            0x25 => opcodes::and_zero_page(&mut self.registers, &self.memory),
            0x26 => opcodes::rol_zero_page(&mut self.registers, &mut self.memory),
            0x27 => opcodes::rla_zero_page(&mut self.registers, &mut self.memory),
            0x28 => opcodes::plp_implied(&mut self.registers, &mut self.memory),
            0x29 => opcodes::and_immediate(&mut self.registers, &self.memory),
            0x2A => opcodes::rol_accumulator(&mut self.registers),
            0x2C => opcodes::bit_absolute(&mut self.registers, &self.memory),
            0x2D => opcodes::and_absolute(&mut self.registers, &self.memory),
            0x2E => opcodes::rol_absolute(&mut self.registers, &mut self.memory),
            0x2F => opcodes::rla_absolute(&mut self.registers, &mut self.memory),
            0x30 => opcodes::bmi_relative(&mut self.registers, &self.memory),
            0x31 => opcodes::and_indirect_y(&mut self.registers, &self.memory),
            0x33 => opcodes::rla_indirect_y(&mut self.registers, &mut self.memory),
            0x34 => opcodes::nop_zero_page_x(&mut self.registers, &self.memory),
            0x35 => opcodes::and_zero_page_x(&mut self.registers, &self.memory),
            0x36 => opcodes::rol_zero_page_x(&mut self.registers, &mut self.memory),
            0x37 => opcodes::rla_zero_page_x(&mut self.registers, &mut self.memory),
            0x38 => opcodes::sec_implied(&mut self.registers),
            0x39 => opcodes::and_absolute_y(&mut self.registers, &self.memory),
            0x3A => opcodes::nop_implied(),
            0x3B => opcodes::rla_absolute_y(&mut self.registers, &mut self.memory),
            0x3C => opcodes::nop_absolute_x(&mut self.registers, &self.memory),
            0x3D => opcodes::and_absolute_x(&mut self.registers, &self.memory),
            0x3E => opcodes::rol_absolute_x(&mut self.registers, &mut self.memory),
            0x3F => opcodes::rla_absolute_x(&mut self.registers, &mut self.memory),
            0x40 => opcodes::rti_implied(&mut self.registers, &self.memory),
            0x41 => opcodes::eor_indirect_x(&mut self.registers, &self.memory),
            0x43 => opcodes::sre_indirect_x(&mut self.registers, &mut self.memory),
            0x44 => opcodes::nop_zero_page(&mut self.registers, &self.memory),
            0x45 => opcodes::eor_zero_page(&mut self.registers, &self.memory),
            0x46 => opcodes::lsr_zero_page(&mut self.registers, &mut self.memory),
            0x47 => opcodes::sre_zero_page(&mut self.registers, &mut self.memory),
            0x48 => opcodes::pha_implied(&mut self.registers, &mut self.memory),
            0x49 => opcodes::eor_immediate(&mut self.registers, &self.memory),
            0x4A => opcodes::lsr_accumulator(&mut self.registers),
            0x4C => opcodes::jmp_absolute(&mut self.registers, &self.memory),
            0x4D => opcodes::eor_absolute(&mut self.registers, &self.memory),
            0x4E => opcodes::lsr_absolute(&mut self.registers, &mut self.memory),
            0x4F => opcodes::sre_absolute(&mut self.registers, &mut self.memory),
            0x50 => opcodes::bvc_relative(&mut self.registers, &self.memory),
            0x51 => opcodes::eor_indirect_y(&mut self.registers, &self.memory),
            0x53 => opcodes::sre_indirect_y(&mut self.registers, &mut self.memory),
            0x54 => opcodes::nop_zero_page_x(&mut self.registers, &self.memory),
            0x55 => opcodes::eor_zero_page_x(&mut self.registers, &self.memory),
            0x56 => opcodes::lsr_zero_page_x(&mut self.registers, &mut self.memory),
            0x57 => opcodes::sre_zero_page_x(&mut self.registers, &mut self.memory),
            0x58 => opcodes::cli_implied(&mut self.registers),
            0x59 => opcodes::eor_absolute_y(&mut self.registers, &self.memory),
            0x5A => opcodes::nop_implied(),
            0x5B => opcodes::sre_absolute_y(&mut self.registers, &mut self.memory),
            0x5C => opcodes::nop_absolute_x(&mut self.registers, &self.memory),
            0x5D => opcodes::eor_absolute_x(&mut self.registers, &self.memory),
            0x5E => opcodes::lsr_absolute_x(&mut self.registers, &mut self.memory),
            0x5F => opcodes::sre_absolute_x(&mut self.registers, &mut self.memory),
            0x60 => opcodes::rts_implied(&mut self.registers, &self.memory),
            0x61 => opcodes::adc_indirect_x(&mut self.registers, &self.memory),
            0x63 => opcodes::rra_indirect_x(&mut self.registers, &mut self.memory),
            0x64 => opcodes::nop_zero_page(&mut self.registers, &self.memory),
            0x65 => opcodes::adc_zero_page(&mut self.registers, &self.memory),
            0x66 => opcodes::ror_zero_page(&mut self.registers, &mut self.memory),
            0x67 => opcodes::rra_zero_page(&mut self.registers, &mut self.memory),
            0x68 => opcodes::pla_implied(&mut self.registers, &self.memory),
            0x69 => opcodes::adc_immediate(&mut self.registers, &self.memory),
            0x6A => opcodes::ror_accumulator(&mut self.registers),
            0x6C => opcodes::jmp_indirect(&mut self.registers, &self.memory),
            0x6D => opcodes::adc_absolute(&mut self.registers, &self.memory),
            0x6E => opcodes::ror_absolute(&mut self.registers, &mut self.memory),
            0x6F => opcodes::rra_absolute(&mut self.registers, &mut self.memory),
            0x70 => opcodes::bvs_relative(&mut self.registers, &self.memory),
            0x71 => opcodes::adc_indirect_y(&mut self.registers, &self.memory),
            0x73 => opcodes::rra_indirect_y(&mut self.registers, &mut self.memory),
            0x74 => opcodes::nop_zero_page_x(&mut self.registers, &self.memory),
            0x75 => opcodes::adc_zero_page_x(&mut self.registers, &self.memory),
            0x76 => opcodes::ror_zero_page_x(&mut self.registers, &mut self.memory),
            0x77 => opcodes::rra_zero_page_x(&mut self.registers, &mut self.memory),
            0x78 => opcodes::sei_implied(&mut self.registers),
            0x79 => opcodes::adc_absolute_y(&mut self.registers, &self.memory),
            0x7A => opcodes::nop_implied(),
            0x7B => opcodes::rra_absolute_y(&mut self.registers, &mut self.memory),
            0x7C => opcodes::nop_absolute_x(&mut self.registers, &self.memory),
            0x7D => opcodes::adc_absolute_x(&mut self.registers, &self.memory),
            0x7E => opcodes::ror_absolute_x(&mut self.registers, &mut self.memory),
            0x7F => opcodes::rra_absolute_x(&mut self.registers, &mut self.memory),
            0x80 => opcodes::nop_immediate(&mut self.registers, &self.memory),
            0x81 => opcodes::sta_indirect_x(&mut self.registers, &mut self.memory),
            0x83 => opcodes::sax_indirect_x(&mut self.registers, &mut self.memory),
            0x84 => opcodes::sty_zero_page(&mut self.registers, &mut self.memory),
            0x85 => opcodes::sta_zero_page(&mut self.registers, &mut self.memory),
            0x86 => opcodes::stx_zero_page(&mut self.registers, &mut self.memory),
            0x87 => opcodes::sax_zero_page(&mut self.registers, &mut self.memory),
            0x88 => opcodes::dey_implied(&mut self.registers),
            0x8A => opcodes::txa_implied(&mut self.registers),
            0x8C => opcodes::sty_absolute(&mut self.registers, &mut self.memory),
            0x8D => opcodes::sta_absolute(&mut self.registers, &mut self.memory),
            0x8E => opcodes::stx_absolute(&mut self.registers, &mut self.memory),
            0x8F => opcodes::sax_absolute(&mut self.registers, &mut self.memory),
            0x90 => opcodes::bcc_relative(&mut self.registers, &mut self.memory),
            0x91 => opcodes::sta_indirect_y(&mut self.registers, &mut self.memory),
            0x94 => opcodes::sty_zero_page_x(&mut self.registers, &mut self.memory),
            0x95 => opcodes::sta_zero_page_x(&mut self.registers, &mut self.memory),
            0x96 => opcodes::stx_zero_page_y(&mut self.registers, &mut self.memory),
            0x97 => opcodes::sax_zero_page_y(&mut self.registers, &mut self.memory),
            0x98 => opcodes::tya_implied(&mut self.registers),
            0x99 => opcodes::sta_absolute_y(&mut self.registers, &mut self.memory),
            0x9A => opcodes::txs_implied(&mut self.registers),
            0x9D => opcodes::sta_absolute_x(&mut self.registers, &mut self.memory),
            0xA0 => opcodes::ldy_immediate(&mut self.registers, &self.memory),
            0xA1 => opcodes::lda_indirect_x(&mut self.registers, &self.memory),
            0xA2 => opcodes::ldx_immediate(&mut self.registers, &self.memory),
            0xA3 => opcodes::lax_indirect_x(&mut self.registers, &self.memory),
            0xA4 => opcodes::ldy_zero_page(&mut self.registers, &self.memory),
            0xA5 => opcodes::lda_zero_page(&mut self.registers, &self.memory),
            0xA6 => opcodes::ldx_zero_page(&mut self.registers, &self.memory),
            0xA7 => opcodes::lax_zero_page(&mut self.registers, &self.memory),
            0xA8 => opcodes::tay_implied(&mut self.registers),
            0xA9 => opcodes::lda_immediate(&mut self.registers, &self.memory),
            0xAA => opcodes::tax_implied(&mut self.registers),
            0xAC => opcodes::ldy_absolute(&mut self.registers, &self.memory),
            0xAD => opcodes::lda_absolute(&mut self.registers, &self.memory),
            0xAE => opcodes::ldx_absolute(&mut self.registers, &self.memory),
            0xAF => opcodes::lax_absolute(&mut self.registers, &self.memory),
            0xBA => opcodes::tsx_implied(&mut self.registers),
            0xB0 => opcodes::bcs_relative(&mut self.registers, &self.memory),
            0xB1 => opcodes::lda_indirect_y(&mut self.registers, &self.memory),
            0xB3 => opcodes::lax_indirect_y(&mut self.registers, &self.memory),
            0xB4 => opcodes::ldy_zero_page_x(&mut self.registers, &self.memory),
            0xB5 => opcodes::lda_zero_page_x(&mut self.registers, &self.memory),
            0xB6 => opcodes::ldx_zero_page_y(&mut self.registers, &self.memory),
            0xB7 => opcodes::lax_zero_page_y(&mut self.registers, &self.memory),
            0xB8 => opcodes::clv_implied(&mut self.registers),
            0xB9 => opcodes::lda_absolute_y(&mut self.registers, &self.memory),
            0xBC => opcodes::ldy_absolute_x(&mut self.registers, &self.memory),
            0xBD => opcodes::lda_absolute_x(&mut self.registers, &self.memory),
            0xBE => opcodes::ldx_absolute_y(&mut self.registers, &self.memory),
            0xBF => opcodes::lax_absolute_y(&mut self.registers, &self.memory),
            0xC0 => opcodes::cpy_immediate(&mut self.registers, &self.memory),
            0xC1 => opcodes::cmp_indirect_x(&mut self.registers, &self.memory),
            0xC3 => opcodes::dcp_indirect_x(&mut self.registers, &mut self.memory),
            0xC4 => opcodes::cpy_zero_page(&mut self.registers, &self.memory),
            0xC5 => opcodes::cmp_zero_page(&mut self.registers, &self.memory),
            0xC6 => opcodes::dec_zero_page(&mut self.registers, &mut self.memory),
            0xC7 => opcodes::dcp_zero_page(&mut self.registers, &mut self.memory),
            0xC8 => opcodes::iny_implied(&mut self.registers),
            0xC9 => opcodes::cmp_immediate(&mut self.registers, &self.memory),
            0xCA => opcodes::dex_implied(&mut self.registers),
            0xCC => opcodes::cpy_absolute(&mut self.registers, &self.memory),
            0xCD => opcodes::cmp_absolute(&mut self.registers, &self.memory),
            0xCE => opcodes::dec_absolute(&mut self.registers, &mut self.memory),
            0xCF => opcodes::dcp_absolute(&mut self.registers, &mut self.memory),
            0xD0 => opcodes::bne_relative(&mut self.registers, &self.memory),
            0xD1 => opcodes::cmp_indirect_y(&mut self.registers, &self.memory),
            0xD3 => opcodes::dcp_indirect_y(&mut self.registers, &mut self.memory),
            0xD4 => opcodes::nop_zero_page_x(&mut self.registers, &self.memory),
            0xD5 => opcodes::cmp_zero_page_x(&mut self.registers, &self.memory),
            0xD6 => opcodes::dec_zero_page_x(&mut self.registers, &mut self.memory),
            0xD7 => opcodes::dcp_zero_page_x(&mut self.registers, &mut self.memory),
            0xD8 => opcodes::cld_implied(&mut self.registers),
            0xD9 => opcodes::cmp_absolute_y(&mut self.registers, &self.memory),
            0xDA => opcodes::nop_implied(),
            0xDB => opcodes::dcp_absolute_y(&mut self.registers, &mut self.memory),
            0xDC => opcodes::nop_absolute_x(&mut self.registers, &self.memory),
            0xDD => opcodes::cmp_absolute_x(&mut self.registers, &self.memory),
            0xDE => opcodes::dec_absolute_x(&mut self.registers, &mut self.memory),
            0xDF => opcodes::dcp_absolute_x(&mut self.registers, &mut self.memory),
            0xE0 => opcodes::cpx_immediate(&mut self.registers, &self.memory),
            0xE1 => opcodes::sbc_indirect_x(&mut self.registers, &self.memory),
            0xE3 => opcodes::isc_indirect_x(&mut self.registers, &mut self.memory),
            0xE4 => opcodes::cpx_zero_page(&mut self.registers, &self.memory),
            0xE5 => opcodes::sbc_zero_page(&mut self.registers, &self.memory),
            0xE6 => opcodes::inc_zero_page(&mut self.registers, &mut self.memory),
            0xE7 => opcodes::isc_zero_page(&mut self.registers, &mut self.memory),
            0xE8 => opcodes::inx_implied(&mut self.registers),
            0xE9 => opcodes::sbc_immediate(&mut self.registers, &self.memory),
            0xEA => opcodes::nop_implied(),
            0xEB => opcodes::sbc_immediate(&mut self.registers, &self.memory),
            0xEC => opcodes::cpx_absolute(&mut self.registers, &self.memory),
            0xED => opcodes::sbc_absolute(&mut self.registers, &self.memory),
            0xEE => opcodes::inc_absolute(&mut self.registers, &mut self.memory),
            0xEF => opcodes::isc_absolute(&mut self.registers, &mut self.memory),
            0xF0 => opcodes::beq_relative(&mut self.registers, &self.memory),
            0xF1 => opcodes::sbc_indirect_y(&mut self.registers, &self.memory),
            0xF3 => opcodes::isc_indirect_y(&mut self.registers, &mut self.memory),
            0xF4 => opcodes::nop_zero_page_x(&mut self.registers, &self.memory),
            0xF5 => opcodes::sbc_zero_page_x(&mut self.registers, &self.memory),
            0xF6 => opcodes::inc_zero_page_x(&mut self.registers, &mut self.memory),
            0xF7 => opcodes::isc_zero_page_x(&mut self.registers, &mut self.memory),
            0xF8 => opcodes::sed_implied(&mut self.registers),
            0xF9 => opcodes::sbc_absolute_y(&mut self.registers, &self.memory),
            0xFA => opcodes::nop_implied(),
            0xFB => opcodes::isc_absolute_y(&mut self.registers, &mut self.memory),
            0xFC => opcodes::nop_absolute_x(&mut self.registers, &self.memory),
            0xFD => opcodes::sbc_absolute_x(&mut self.registers, &self.memory),
            0xFE => opcodes::inc_absolute_x(&mut self.registers, &mut self.memory),
            0xFF => opcodes::isc_absolute_x(&mut self.registers, &mut self.memory),
            _ => panic!("Unknown opcode {}", opcode)
        }
    }
}